INSERT INTO emp01.ttablacol (ttc_id, tbl_id, ttc_name, ttc_label) VALUES (1, 5, 'us_name', 'Nombre cuenta de usuario');
INSERT INTO emp01.ttablacol (ttc_id, tbl_id, ttc_name, ttc_label) VALUES (2, 5, 'us_pass', 'Clave de Usuario');
INSERT INTO emp01.ttablacol (ttc_id, tbl_id, ttc_name, ttc_label) VALUES (3, 5, 'us_datecreated', 'Fecha de creación');
INSERT INTO emp01.ttablacol (ttc_id, tbl_id, ttc_name, ttc_label) VALUES (4, 5, 'us_status', 'Estado del usuario');
INSERT INTO emp01.ttablacol (ttc_id, tbl_id, ttc_name, ttc_label) VALUES (5, 5, 'us_statusclave', 'Estado de la clave de usuario');
INSERT INTO emp01.ttablacol (ttc_id, tbl_id, ttc_name, ttc_label) VALUES (6, 5, 'us_nomapel', 'Nombres del Usuario');
INSERT INTO emp01.ttablacol (ttc_id, tbl_id, ttc_name, ttc_label) VALUES (7, 2, 'emp_ruc', 'RUC');
INSERT INTO emp01.ttablacol (ttc_id, tbl_id, ttc_name, ttc_label) VALUES (8, 2, 'emp_razonsocial', 'Razón Social');
INSERT INTO emp01.ttablacol (ttc_id, tbl_id, ttc_name, ttc_label) VALUES (9, 2, 'emp_nombrecomercial', 'Nombre Comercial');
INSERT INTO emp01.ttablacol (ttc_id, tbl_id, ttc_name, ttc_label) VALUES (10, 2, 'emp_fechaautorizacion', 'Fecha de autorización');
INSERT INTO emp01.ttablacol (ttc_id, tbl_id, ttc_name, ttc_label) VALUES (11, 1, 'cnt_ruc', 'RUC');
INSERT INTO emp01.ttablacol (ttc_id, tbl_id, ttc_name, ttc_label) VALUES (12, 1, 'cnt_razonsocial', 'Razón Social');
INSERT INTO emp01.ttablacol (ttc_id, tbl_id, ttc_name, ttc_label) VALUES (13, 1, 'cnt_telf', 'Teléfono');
INSERT INTO emp01.ttablacol (ttc_id, tbl_id, ttc_name, ttc_label) VALUES (14, 1, 'cnt_email', 'Email');
INSERT INTO emp01.ttablacol (ttc_id, tbl_id, ttc_name, ttc_label) VALUES (15, 1, 'cnt_dirmatriz', 'Dirección Matriz');
INSERT INTO emp01.ttablacol (ttc_id, tbl_id, ttc_name, ttc_label) VALUES (16, 1, 'cnt_clase', 'Clase del contribuyente');
INSERT INTO emp01.ttablacol (ttc_id, tbl_id, ttc_name, ttc_label) VALUES (17, 1, 'cnt_nrocntespecial', 'Nro Contrib Especial');
INSERT INTO emp01.ttablacol (ttc_id, tbl_id, ttc_name, ttc_label) VALUES (18, 1, 'cnt_oblcontab', 'Obligado LLevar Contabilidad');
INSERT INTO emp01.ttablacol (ttc_id, tbl_id, ttc_name, ttc_label) VALUES (19, 1, 'cnt_nombrecomercial', 'Nombre Comercial');