INSERT INTO emp01.trol (rl_id, rl_name, rl_desc, rl_abreviacion, rl_grupo) VALUES (10, 'CREAR USUARIO', 'PERMITE DAR DE ALTA UN USUARIO EN EL SISTEMA', 'CREATEUSER', 0);
INSERT INTO emp01.trol (rl_id, rl_name, rl_desc, rl_abreviacion, rl_grupo) VALUES (12, 'EDITAR USUARIO', 'PERMITE CAMBIAR EL NOMBRE DE LA CUENTA Y LOS NOMBRES Y APELLIDOS', 'EDITUSER', 0);
INSERT INTO emp01.trol (rl_id, rl_name, rl_desc, rl_abreviacion, rl_grupo) VALUES (13, 'RESETEAR CLAVE', 'PERMITE RESETEAR LA CLAVE DE UN USUARIO', 'RESETCLAVE', 0);
INSERT INTO emp01.trol (rl_id, rl_name, rl_desc, rl_abreviacion, rl_grupo) VALUES (1, 'ACCESO REPORTES', null, 'ACCESREPORTES', 0);
INSERT INTO emp01.trol (rl_id, rl_name, rl_desc, rl_abreviacion, rl_grupo) VALUES (15, 'EDICIÓN DE CONTRIBUYENTES', null, 'EDITCONTRIB', 0);
INSERT INTO emp01.trol (rl_id, rl_name, rl_desc, rl_abreviacion, rl_grupo) VALUES (14, 'CREACIÓN DE CONTRIBUYENTES', null, 'CREACONTRIB', 0);
INSERT INTO emp01.trol (rl_id, rl_name, rl_desc, rl_abreviacion, rl_grupo) VALUES (16, 'CREACIÓN AUTORIZACIONES', null, 'CREAAUT', 0);
INSERT INTO emp01.trol (rl_id, rl_name, rl_desc, rl_abreviacion, rl_grupo) VALUES (18, 'CREACIÓN DE DOCUMENTOS', null, 'CREADOC', 0);
INSERT INTO emp01.trol (rl_id, rl_name, rl_desc, rl_abreviacion, rl_grupo) VALUES (17, 'EDICIÓN DE AUTORIZACIONES', null, 'EDITAUT', 0);
INSERT INTO emp01.trol (rl_id, rl_name, rl_desc, rl_abreviacion, rl_grupo) VALUES (19, 'ACTUALIZACIÓN DE DOCUMENTOS', null, 'UPDATEDOC', 0);
INSERT INTO emp01.trol (rl_id, rl_name, rl_desc, rl_abreviacion, rl_grupo) VALUES (2, 'EDICION DATOS ESTABLECIMIENTO GRÁFICO', null, 'EMPRESAEDIT', 0);
INSERT INTO emp01.trol (rl_id, rl_name, rl_desc, rl_abreviacion, rl_grupo) VALUES (3, 'LISTADO DE CONTRIBUYENTES', null, 'LISTACONTRIB', 0);
INSERT INTO emp01.trol (rl_id, rl_name, rl_desc, rl_abreviacion, rl_grupo) VALUES (4, 'LISTADO DE AUTORIZACIONES', null, 'LISTAAUT', 0);
INSERT INTO emp01.trol (rl_id, rl_name, rl_desc, rl_abreviacion, rl_grupo) VALUES (5, 'LISTADO DE USUARIOS', null, 'LISTAUSER', 0);
INSERT INTO emp01.trol (rl_id, rl_name, rl_desc, rl_abreviacion, rl_grupo) VALUES (6, 'LISTADO DE DOCUMENTOS', null, 'LISTADOC', 0);
INSERT INTO emp01.trol (rl_id, rl_name, rl_desc, rl_abreviacion, rl_grupo) VALUES (7, 'ACCESO PLANTILLAS', null, 'ACCESPLANTILLAS', 0);